public class Clemens
{
    private int anger;
    

    public void seeJaden(boolean visiable)
    {
        if (visiable)
        {
            this.anger += 1000;
        }
        else
        {
            this.anger += 1000;
        }

        public int getStrenght()
        {
            return this.anger*100;
        }

        public int getVoiceLevel
        {
            return this.anger/3;
        }
    }
}